library(shiny)
library(shinydashboard)
library(shinythemes)
library(shinyalert)
library(ggplot2)
library(dplyr)
library(plotly)
library(datasets)
library(d3heatmap)
library(readr)
library(stats)
library(shinyjs)
library(gdata)
library(deSolve)
library(rootSolve)
library(tidyr)
library(MASS)
library(car)
library(rgl)
library(contoureR)
library(optimization)
options(warn = -1)
options(shiny.maxRequestSize = 30 * 1024 ^ 2)
